title: Welcome :)
logo: /assets/logo_small_bw.png
description: You must do what you enjoy, otherwise it's difficult to persist for 5 or 10 years. If you succeed during this period, whether it's because of your own efforts or because you caught a good opportunity, that's great! If not, you've been doing what you like all along, and there's nothing to complain about. If you don't enjoy what you're doing, such as chasing current trends in hopes of easier success, then if you don't ultimately achieve it, you've wasted all your time.
theme: jekyll-theme-minimal
layout: single
classes: wide
