title: Liqun Li
logo: /assets/logo_small_bw.png
description: Pursuing your passion is essential for maintaining long-term commitment over five to ten years. Achieving success—whether through hard work or by seizing fortunate opportunities—is undoubtedly rewarding. Even if you don’t attain success, following what you love ensures you have no regrets. In contrast, chasing trends for easier success without enjoying the process can lead to wasted time and eventual feelings of unfulfillment.
theme: jekyll-theme-minimal
layout: single
classes: wide
