title: Liqun Li
logo: /assets/logo_small_bw.png
description: Pursuing your passion is essential for long-term commitment. Success over 5-10 years may result from hard work or seizing opportunities, but even without it, there's no regret in doing what you enjoy. Chasing trends for easier success without enjoying the process risks wasting time and feeling unfulfilled.
theme: jekyll-theme-minimal
layout: single
classes: wide
