title: Liqun Li
logo: /assets/logo_small_bw.png
description: Pursuing your passion is essential for long-term commitment over 5-10 years. If you achieve success, no matter due to your hard work or luckily seizing opportunities, that is great. Even without success, there's no regret in doing what you enjoy. Chasing trends for easier success without enjoying the process risks wasting time and feeling unfulfilled in the end.
theme: jekyll-theme-minimal
layout: single
classes: wide
